### ISSUE TITLE
Travis CI: notification config needs to be updates

### ISSUE THREAD

**Issue by waja** [nagios-plugins/nagios-plugins#196]
In https://github.com/nagios-plugins/nagios-plugins/blob/master/.travis.yml#L51-L59 you have configured to notify a different team. Please consider to fix it.

```
notifications:
  irc:
    channels:
      - "chat.freenode.net#Monitoring-Plugins"
    on_success: change
    on_failure: always
    skip_join: true
  email:
    - team@monitoring-plugins.org
```
