### ISSUE TITLE
Travis CI: coverity config needs to be updates

### ISSUE THREAD

**Issue by waja** [nagios-plugins/nagios-plugins#197]
In https://github.com/nagios-plugins/nagios-plugins/blob/master/.travis.yml#L70-L72 you have configured to notify a different team. Please consider to fix it.

```
addons:
  coverity_scan:
    project:
      name: "monitoring-plugins/monitoring-plugins"
      description: "Monitoring Plugins"
    notification_email: team@monitoring-plugins.org
```
